version: '3.8'

services:
  app:
    image: 'akmal23/spring-tes:3.0'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=lala
      - POSTGRES_PASSWORD=1234
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/customer_db
      - SPRING_DATASOURCE_USERNAME=lala
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "6868:8080"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=lala
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=customer_db
    ports:
      - "5433:5432"