# Database settings
#spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/customer_db
#spring.datasource.username=lala
#spring.datasource.password=1234
#ENV_URL_CONNECTION=jdbc:oracle:10.20.212.3:5212
#ENV_USER_NAME=lala
#ENV_PASSWORD=1234532lala
# Hibernate properties
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update

#configuration database
#spring:
#  datasource:
#    hikari:
#      connection-timeout: 20000
#      maximum-pool-size: 5
#    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}
##    url: jdbc:postgresql://localhost:5432/customer_db
##    username: lala
##    password: 1234
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database: postgresql
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#server:
#  port: 8080
##config file upload
#---
#spring:
#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2KB
#      max-file-size: 200MB
#      max-request-size: 215MB
##folder location save file
#file:
#  upload-dir: /home/dicka/Documents/project-java/spring-reactjs/uploads

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8080
# Other application-specific configurations